package com.fontar.data.impl.domain.bean;

// Generated 04/08/2006 16:39:48 by Hibernate Tools 3.1.0 beta3

import java.math.BigDecimal;

/**
 * ClavesPaqueteResultado generated by hbm2java
 */

public class ClavesPaqueteResultado implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private BigDecimal usuario;

	private String clave;

	public String getClave() {
		return clave;
	}

	public void setClave(String clave) {
		this.clave = clave;
	}

	public BigDecimal getUsuario() {
		return usuario;
	}

	public void setUsuario(BigDecimal usuario) {
		this.usuario = usuario;
	}

}
