package com.fontar.data.impl.domain.bean;

// Generated 04/08/2006 16:39:48 by Hibernate Tools 3.1.0 beta3

/**
 * Usuario generated by hbm2java
 */

public class ClavesBean implements java.io.Serializable {
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private Long id = null;

	private String nombreUsuario;

	private String bean;

	private byte[] clave;

	public ClavesBean(){
		super();
	}
	
	public ClavesBean(String dataType, String userName, byte[] secretKey) {
		this.bean = dataType;
		this.nombreUsuario = userName;
		this.clave = secretKey;
	}

	public byte[] getClave() {
		return clave;
	}

	public void setClave(byte[] clave) {
		this.clave = clave;
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getNombreUsuario() {
		return nombreUsuario;
	}

	public void setNombreUsuario(String nombreUsuario) {
		this.nombreUsuario = nombreUsuario;
	}

	public String getBean() {
		return bean;
	}

	public void setBean(String bean) {
		this.bean = bean;
	}

}
