package com.fontar.data.impl.domain.bean;

// Generated 04/08/2006 16:39:48 by Hibernate Tools 3.1.0 beta3

/**
 * ClavesPaqueteEvaluador generated by hbm2java
 */

public class ClavesPaqueteEvaluador implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private long idUsuario;

	private byte[] clave;

	public byte[] getClave() {
		return clave;
	}

	public void setClave(byte[] clave) {
		this.clave = clave;
	}

	public long getIdUsuario() {
		return idUsuario;
	}

	public void setIdUsuario(long idUsuario) {
		this.idUsuario = idUsuario;
	}
}
