package com.fontar.data.impl.domain.bean;

/**
 * Usuario generated by hbm2java
 */

public class CriptoTestPassBean implements java.io.Serializable {
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private long id;

	private long idUsuario;

	private byte[] clave;

	private String tabla;

	public byte[] getClave() {
		return clave;
	}

	public void setClave(byte[] clave) {
		this.clave = clave;
	}

	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public long getIdUsuario() {
		return idUsuario;
	}

	public void setIdUsuario(long idUsuario) {
		this.idUsuario = idUsuario;
	}

	public String getTabla() {
		return tabla;
	}

	public void setTabla(String tabla) {
		this.tabla = tabla;
	}

}
