package com.pragma.util;

import java.util.Date;

import javax.servlet.http.HttpServletRequest;

import com.pragma.util.BeanUtils.BeanUtils;



public class WebUtils {
	
	public static String toSafeHTML(String s) {
		s = s.replace("\n", "<br/>");
		s = s.replace("\t", "&#09;");
		s = s.replace(" ", "&nbsp;");
		s = s.replace("<", "&lt;");
		s = s.replace(">", "&gt;");
		return s;
	}

    /**
     * devuelve una cadena que incluye comillas en los extremos, escapeo de los
     * caracteres y cadenas inseguras.
     * @param str
     * @return
     */
    public static String toSafeQuotedJavascriptString(String str) {
	//Barras
	str = StringUtil.replace(str, "\\", "\\\\");
	//Comillas simples
	str = StringUtil.replace(str, "'", "\\'");
	//Comillas dobles
	str = StringUtil.replace(str, "\"", "\\\"");
	//Retornos de carro
	str = StringUtil.replace(str, "\n", "\\n");
	//Tabulaciones
	str = StringUtil.replace(str, "\t", "\\t");
	//Tags de html que pueden dar problemas
	str = StringUtil.replace(str, "<", "<'+'");
	
	return "'"+str+"'";
	
	
    }
    
    public static String toJSCode(String s) {
	return toSafeQuotedJavascriptString(s);
    }
    
    public static String toJSCode(Date date) {
	return "(new Date("+date.getTime()+"))";
    }
    
    public static String toJSCode(Object o) {
	if(o==null) return "null";
	if(o instanceof Number) {
	    return o.toString();
	}
	if(o instanceof Date) {
	    return toJSCode((Date)o);
	}
	return toSafeQuotedJavascriptString(o.toString());
    }
    public static Object getComplexAttribute(HttpServletRequest request, String attribute) {
    	if(attribute==null) return request.getAttribute(null);
    	else {
    		String[] parts = attribute.split("\\.");
    		Object o = request.getAttribute(parts[0]);
    		if(parts.length>1) {
    			return BeanUtils.getProperty(o, attribute.substring(attribute.indexOf('.')+1));
    		} else {
    			return o;
    		}
    	}
    }
    
    public static String randomId() {
    	return "autogeneratedId"+((long)Math.round(Math.random()*100000000.0));
    }
}

